[General]
network = flora.simulations.CSMAAvec2RetransmissionUnconfirmed59B.DtSIot
sim-time-limit = 900s  # duree maximale de la simulation 9 minutes.
simtime-resolution = -11 # la plus petite unite de temps que la simulation peut representer 10 -11 secondes

**.vector-recording = false # Les vecteurs sont des series de valeurs enregistrees au fil du temps pour certains parametres ou signaux

**.scalar-recording = true #  l enregistrement des scalars par defaut pour tous les modules (non mentionnees dans les regles ci dessus)

repeat = 30
seed-set = ${repetition}  # (seed) du generateur de nombres aleatoires pour la simulation, ce qui controle tous les evenements aleatoires (comme l intervalle entre les paquets, l ordre de transmission, etc.)

###########################
# General
###########################
rng-class = "cMersenneTwister"  # C est un generateur de nombres aleatoires base sur l algorithme Mersenne Twister

# Radio and Medium
*.LoRaMedium.pathLoss.typename = "FreeSpacePathLoss" # "LoRaLogNormalShadowing"
*.LoRaMedium.propagation.typename = "DtSIoTPropagation" # SatellitePropagation
*.LoRaMedium.**.maxTransmissionDuration = 4s # duree maximale autorisee pour une transmission radio

*.LoRaMedium.**.minInterferenceTime = 0s # duree minimale de chevauchement temporel entre deux signaux pour qu ils soient consideres comme interferents. tout chevauchement est traite comme une interference.
**.displayAddresses = false # desactive l affichage des adresses reseau dans l interface graphique

# Visualizer
*.visualizer.*.radioVisualizer.displayAntennaLobes = true # active l affichage des lobes de rayonnement des antennes radio
*.visualizer.*.dataLinkVisualizer.displayLinks = true
*.visualizer.*.mobilityVisualizer.displayMovementTrails = true
*.visualizer.*.mobilityVisualizer.movementTrailLineWidth = 1
*.visualizer.*.mobilityVisualizer.trailLength = 3000
###########################
# LoRa GW (satellites) 
###########################
**.nrOfGW = 1

**.loRaGW[*].**.initFromDisplayString = false # ne doivent pas initialiser leurs parametres a partir du displayString (position, orientation, etc.).
# LoRa Radio
*.loRaGW[*].LoRaGWNic.radio.separateTransmissionParts = false # tout le paquet est transmis comme un seul bloc, plus simple et rapide a simuler. INET ne simule pas separement les differentes parties de la trame (preambule, header, payload).
*.loRaGW[*].LoRaGWNic.radio.separateReceptionParts = false # meme pour la reception

*.loRaGW[*].LoRaGWNic.radio.antenna.gain = 12dB # le gain de l antenne est de 12 decibels.
*.loRaGW[*].LoRaGWNic.radio.antenna.maxGain = 12dB
*.loRaGW[*].LoRaGWNic.radio.antenna.minGain = 1dB
*.loRaGW[*].LoRaGWNic.radio.antenna.beamWidth = 120deg # l antenne emet ou recoit sur un angle de 120 deg.
*.loRaGW[*].LoRaGWNic.radio.antenna.mobility.offsetHeading = 120deg # l antenne est decalee de 120deg par rapport a la direction de mouvement ou de reference du satellite.

*.loRaGW[*].LoRaGWNic.radio.iAmGateway = true # le noeud radio est configure comme une passerelle (gateway). 

# Application
**.loRaGW[*].numUdpApps = 1
**.loRaGW[*].packetHandler.destAddresses = "networkServer"
**.loRaGW[*].packetHandler.destPort = 1000
**.loRaGW[*].packetHandler.localPort = 2000

# Mobility - orbite plus basse
*.loRaGW[*].mobility.faceForward = false # la direction du satellite ou de son antenne peut etre independante de sa trajectoire.
*.loRaGW[*].mobility.updateInterval = 20s # toutes les 20 secondes de simulation, la position, la vitesse et eventuellement l orientation du satellite sont recalculees.

# constellation general parameters, argument of perigee is set to 0
*.loRaGW[*].NoradModule.baseYear = 20   # Le satellite est configure avec une annee de reference 2020 pour le calcul de sa position orbitale via le module NORAD.
*.loRaGW[*].NoradModule.baseDay = 0.8194444

*.loRaGW[*].NoradModule.satName = "FLoRaSat"
*.loRaGW[*].NoradModule.planes = 1
*.loRaGW[*].NoradModule.satPerPlane = 1
*.loRaGW[*].NoradModule.epochYear = 20 # L epoch du satellite est fixee a l annee 2020, servant de reference pour le calcul de sa position orbitale initiale.
*.loRaGW[*].NoradModule.epochDay = 0.8194444
*.loRaGW[*].NoradModule.eccentricity = 0.000001 # l orbite du satellite est quasiment circulaire
*.loRaGW[*].NoradModule.inclination = 97.4 # l inclinaison orbitale du satellite.
*.loRaGW[*].NoradModule.altitude = 600  

# Single pass satellite
*.loRaGW[0].NoradModule.raan = 340 # Le noeud ascendant du satellite est fixe a 320 deg, definissant la position initiale de l orbite par rapport a l equateur.
*.loRaGW[0].NoradModule.meanAnomaly = 317 # un parametre orbital qui indique la position du satellite sur son orbite a un instant donne, en degres, par rapport au perigee.
*.loRaGW[0].*.satIndex = 0 # definit l indice du satellite.

###########################
# LoRa Nodes (devices on ground) 
###########################
#**.nrOfNodes = ${N= 20}
**.nrOfNodes = ${N=20, 50, 100, 200, 400, 600, 800, 1000}


# Application
**.numberOfPacketsToSend = 0  # 0 means infinite number of packets
**.timeToFirstPacket = intuniform(0s, 60s)    # Le delai avant l envoi du premier paquet par chaque noeud est choisi aleatoirement entre 0 et 60s pour repartir les transmissions dans le temps.
**.timeToNextPacket = intuniform(120s, 300s)    
**.usingAck = false            # Avec acquittement.

# LoRa Bandwith
*.loRaNodes[*].**.initialLoRaBW = 125 kHz
# LoRa Transmission Power 
*.loRaNodes[*].**.initialLoRaTP = 14dBm 
# LoRa Spreading Factor (9-12)
*.loRaNodes[*].**.initialLoRaSF = 10

# LoRa Coding Rate
*.loRaNodes[*].**.initialLoRaCR = 4
# LoRa payload
*.loRaNodes[*].**.payloadSize = 59B

*.loRaNodes[*].LoRaNic.mac.withRetransmission = true
*.loRaNodes[*].LoRaNic.mac.maxRetransmissions = 2

**.alohaChannelModel = false 
# Activation CSMA
*.loRaNodes[*].LoRaNic.mac.useCSMA = true

# Parametres CSMA selon Table 1
*.loRaNodes[*].LoRaNic.mac.difsCount = 2           # 2 CADs
*.loRaNodes[*].LoRaNic.mac.backoffMax = 6          # 6 slots max
*.loRaNodes[*].LoRaNic.mac.maxChanges = 6          # 6 changements canal max

*.loRaGW[*].LoRaGWNic.radio.transmitter.power = 0.025W
# LoRa Other params
*.loRaNodes[*].**.initFromDisplayString = false # les noeuds LoRa ne vont pas initialiser leurs parametres a partir de la chaine d affichage graphique (display string)
*.loRaNodes[*].**.evaluateADRinNode = false # chaque noeud LoRa va adapter automatiquement son debit et sa puissance d emission en fonction de la qualite de la liaison avec le satellite ou la passerelle.
*.loRaNodes[*].LoRaNic.mac.classUsed = "A"

# LoRa Node and Gateway Radio and Medium
*.loRaNodes[*].*.radio.separateTransmissionParts = false # la transmission radio n est pas decoupee en parties distinctes (comme preambule, en-tete, donnees).
*.loRaNodes[*].*.radio.separateReceptionParts = false
*.loRaNodes[*].*.radio.radioMediumModule = "LoRaMedium" # simule le comportement reel d un canal LoRa.

# Power
*.loRaNodes[*].LoRaNic.radio.energyConsumer.typename = "LoRaEnergyConsumer" # pour simuler la consommation d energie de sa radio.
*.loRaNodes[*].**.energySourceModule = "IdealEpEnergyStorage" # chaque noeud LoRa utilise une source d energie de type IdealEpEnergyStorage.
*.loRaNodes[*].LoRaNic.radio.energyConsumer.configFile = xmldoc("energyConsumptionParameters.xml") # precise combien d energie chaque action consomme.

# Mobility
# Random uniform disk initilization is the default mobility
*.loRaNodes[*].mobility.radius = 15.0 # chaque noeud mobile se deplace sur un cercle de rayon 15 metres
*.loRaNodes[*].mobility.centerLatitude = -16 # l atitude du centre du cercle autour duquel les noeuds se deplacent.
*.loRaNodes[*].mobility.centerLongitude = -56.5


*.loRaGW[*].networkServer.localPort = 1000
*.loRaGW[*].networkServer.destPort = 2000
*.loRaGW[*].networkServer.evaluateADRinServer = false
*.loRaGW[*].networkServer.adrMethod = "avg"
*.loRaGW[*].networkServer.adrDeviceMargin = 10
*.loRaGW[*].networkServer.WorkWithAck = false








